theme: jekyll-theme-minimal
# Or try others: jekyll-theme-merlot, jekyll-theme-cayman, jekyll-theme-architect, etc.
# Full list: https://pages.github.com/themes/
title: Church Docs
description: Docs for First Baptist Corsicana
