site_name: Church Documents

theme:
  name: material
  palette:
    - scheme: slate
      primary: blue grey
      accent: amber

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - tables

nav:
  - Home: index.md
  - Bylaws: bylaws/index.md
  - Constitution: constitution/index.md
  - Policies: policies/index.md
  - Jobs:
    - Overview: jobs/index.md
    - Custodial:
      - Overview: jobs/custodial/index.md
      - Children: jobs/custodial/job-custodial-children.md
      - Facility: jobs/custodial/job-custodial-facility.md
      - FLC: jobs/custodial/job-custodial-flc.md
      - Lead: jobs/custodial/job-custodial-lead.md
    - Ministerial:
      - Overview: jobs/ministerial/index.md
    - Program:
      - Overview: jobs/program/index.md
      - Worship: jobs/program/job-support-worship.md
    - Support:
      - Overview: jobs/support/index.md
      - Clerk: jobs/support/job-support-clerk.md
      - Financial: jobs/support/job-support-financial.md
      - FLC One: jobs/support/job-support-flc-one.md
      - FLC Two: jobs/support/job-support-flc-two.md
      - Media: jobs/support/job-support-media.md
      - Temp: jobs/support/job-support-temp.md
    - Template: jobs/job-template.md
